### ISSUE TITLE
Buzzer

### ISSUE THREAD

**Issue by mjoinsd** [migdyn/rwcookingtimer#1]
Please allow to change the buzzer, with non-abusive sounds - this one wakes my daughter.

**Comment by migdyn** [comment]
It's on my TODO list.
Meanwhile, you can open the plugin JAR file with an archiver like 7-Zip (if you're using Windows) and replace the time_up.ogg file.

**Comment by mjoinsd** [comment]
DUDE!!!  YOU ROCK! THANKS! :P

Thanks,

mj

Mark John "mj” Ostrum

mj@seekingrealtruth.net
858 229 2713 (m)

**Comment by mjoinsd** [comment]
uh.  how to i make ogg file?  (And I have a degree in Software Engineering- but have been dealing with serious health issues lately)

Thanks,

mj

Mark John "mj” Ostrum

mj@seekingrealtruth.net
858 229 2713 (m)

**Comment by migdyn** [comment]
You can use the export feature in Audacity.

**Comment by mjoinsd** [comment]
Here ya go - a fun one.

Thanks,

mj

Mark John "mj” Ostrum

mj@seekingrealtruth.net
858 229 2713 (m)

**Comment by mjoinsd** [comment]
but i broke it. :(

Mac OS X 10.13.4  Java: 1.8.0_121 x86_64 0.9.2.7_39  -H:4096 -D:3072  (Steam)
______________________________________________________________________
LoadingState: Error occurred while starting singleplayer game
pluginapi.PluginException: No 'plugin.yml' definition file found for plugin "CookingTimer.v0.2.3.jar"! 
If you are the creator of this plugin, you have to put a proper 'plugin.yml' file into the "resources" package
	at pluginapi.PluginLoader.loadPluginFromJar(SourceFile:198)
	at pluginapi.PluginLoader.loadPlugins(SourceFile:46)
	at pluginapi.PluginManager.initialize(SourceFile:72)
	at w.m.c(SourceFile:308)
	at w.m.a(SourceFile:174)
	at w.i.a(SourceFile:206)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


Thanks,

mj

Mark John "mj” Ostrum

mj@seekingrealtruth.net
858 229 2713 (m)

**Comment by migdyn** [comment]
What happens when you run a game with the edited plugin? Does it crash?

**Comment by mjoinsd** [comment]
yes.

Thanks,

mj

Mark John "mj” Ostrum

mj@seekingrealtruth.net
858 229 2713 (m)

**Comment by migdyn** [comment]
Could you post the crash log?

**Comment by migdyn** [comment]
The new update is available for download. The sounds are now in a separate directory and can be easily replaced.

**Comment by mjoinsd** [comment]
Cool!

**Comment by mjoinsd** [comment]
how do i package and property deploy this then once I change the sound I want?

Thanks,

mj

Mark John "mj” Ostrum

mj@seekingrealtruth.net
858 229 2713 (m)

**Comment by migdyn** [comment]
the sounds are loaded from the assets folder that **has to be located in the same directory as the JAR!**
after you replace the sound you can run the game and it should work.
